version: '3'

services:
  steampipe:
    build:
      context: .
      args:
        PLUGINS: aws
    # command: ["service", "start", "--foreground", "--show-password"]
    command: ["steampipe", "service", "start", "--foreground", "--dashboard", "--dashboard-listen=network"]
    restart: unless-stopped
    ports:
      - 9193:9193
      - 9194:9194
    volumes:
      - ./conf/steampipe:/home/steampipe/.steampipe/config
      - ./conf/mods:/home/steampipe/.steampipe/mods
    environment:
      - STEAMPIPE_DATABASE_PASSWORD=steampipe
      - STEAMPIPE_CACHE=true
      - STEAMPIPE_CACHE_MAX_SIZE_MB=4096
      - STEAMPIPE_CACHE_TTL=300
      - STEAMPIPE_QUERY_TIMEOUT=120
      - STEAMPIPE_MAX_PARALLEL=10
      - STEAMPIPE_WORKSPACE=aws_insights # aws_insights, aws_compliance
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"